repos:
  - repo: https://github.com/pycqa/isort
    rev: 6.1.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "120"]

  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        language_version: python3
        args: ["--line-length", "120"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff-check
        args: ["--fix"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json

  # Frontend hooks
  - repo: local
    hooks:
      - id: typescript-check
        name: TypeScript type checking
        entry: bash -c 'cd iris && npx tsc --noEmit'
        language: system
        files: '^iris/src/.*\.(ts|tsx)$'
        pass_filenames: false

      - id: react-build
        name: React build check
        entry: bash -c 'cd iris && npm run build'
        language: system
        files: '^iris/(src/.*\.(ts|tsx)|package\.json|tsconfig\.json|vite\.config\.js)$'
        pass_filenames: false
