[tool.ruff]
line-length = 88
target-version = "py310"
extend-ignore = ["E203", "W503"]

# You can tune which rules are enabled/disabled here. Keep defaults minimal
# for now; teams can extend this file later.
exclude = [
  "docs",
  "preview",
  "demo/*/*.iris",
]
