name: Lint

on:
  push:
    branches:
      - master
      - testci
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install pre-commit + tools
        run: python -m pip install --upgrade pip pre-commit black isort ruff
      - name: Run isort (show diff, non-blocking)
        continue-on-error: true
        run: isort --diff .
        # someday, to enforce
        # run: isort --check-only .
      - name: Run black (show diff, non-blocking)
        continue-on-error: true
        run: black --diff .
        # someday, to enforce
        # run: black --check .
      - name: Run pre-commit (ruff + hooks, show diffs)
        continue-on-error: true
        run: pre-commit run --all-files --show-diff-on-failure
        # someday, to enforce: rm throughout file c-o-e: true
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install Node.js dependencies
        working-directory: iris
        run: npm install
      
      - name: TypeScript type checking
        working-directory: iris
        run: npx tsc --noEmit
