name: CI

on:
  push:
    branches:
      - master
      - initial_tweaks
  pull_request:
    branches:
      - master
  schedule:
    - cron: "9 16 * * 1"

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        #os: [ubuntu-latest] #, macos-latest, windows-latest]
        runs-on: "ubuntu-latest"
        python-version: ["3.9", "3.10"]
    name: "🐍 ${{ matrix.python-version }} • ${{ matrix.runs-on }}"
    runs-on: ${{ matrix.runs-on }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install IRIS
      run: pip install .  #'.[test]'

    - name: Demo test
      run: |
        iris demo

    - name: Test with pytest
      if: false
      run: |
        pip install pytest pytest-flask==0.15.1
        pytest
